### ISSUE TITLE
Add zsh-autosuggestions module

### ISSUE THREAD

**Issue by Hotschke** [Eriner/zim#35]
I like following zsh script which offers based on the zsh-history a possible completion candidate which can be accepted with `<ctrl-f>`.

https://github.com/tarruda/zsh-autosuggestions

It feels like advertised unobtrusive and fast.

What I like most about zim compared to the many other zsh frameworks, is its speed. So I do not want to suggest feature creep or new modules which slow zim down which would undermine the spirit of zim.
Any critical thoughts are welcome.

**Comment by Eriner** [comment]
This seems like something I may include. Let me play with it (and test speed/usability) over the next few days.

**Comment by Hotschke** [comment]
Thanks for considering it.

BTW, the repository has moved to https://github.com/zsh-users/zsh-autosuggestions

**Comment by Eriner** [comment]
Yeah, no problem. I may let it mature a bit and may even do some work on it myself; would be nice to integrate syntax-highlighting into it, if that hasn't already been done. But at some point, this will most definitely get pulled into zim. I like this feature in fish. Moving this into Zsh is extremely cool; a combination of history-substring-search, syntax-highlighting, and zsh-autosuggestions makes for a (basically) close-to-POSIX fish shell. Good stuff being done by zsh-users.

**Comment by Eriner** [comment]
I took a look at this again. It seems there are still a few bugs to be worked out. Additionally, there's a proposal to implement async support. I would really like to have that as a feature before I implement it here. One of the main goals of zim is to keep things fast.

**Comment by Eriner** [comment]
As an update, I'm waiting for the following issues to be resolved (as the minimum requirement for inclusion):

- [ ] [pasting is slow when using bracketed-paste-magic](https://github.com/zsh-users/zsh-autosuggestions/issues/141)
- [ ] [plugin's strange behavior after commands with unicode character](https://github.com/zsh-users/zsh-autosuggestions/issues/155)
- [ ] [Evals need escaping](https://github.com/zsh-users/zsh-autosuggestions/issues/152)

There may be additional issues that are discovered between now and the time of inclusion. I will do my best to add those to the list above. Additionally, more issues may arise when combining this with zsh-syntax-highlighting.

I will re-evaluate this in a couple of weeks.

**Comment by lnicola** [comment]
I'm using `zsh-autosuggestions` and https://github.com/zsh-users/zsh-autosuggestions/issues/136 made using `mc` terrible.

**Comment by bijancn** [comment]
Can't this be an optional module? I am using it for months and can't live without it any more. I don't care about midnight commander or "pasting is slow" e.g.

Currently I have to load and update it myself via
```
if [[ ! -d ~/zsh-autosuggestions ]]; then
  git clone git://github.com/zsh-users/zsh-autosuggestions ~/zsh-autosuggestions
fi
source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
```
Would be great if zim could support this even if only as experimental feature or something like that.

**Comment by ratheesh** [comment]
@Eriner 
+1 bijancn

I will really helpful to add this module with disabled by default. People who are used to it find it very helpful.

**Comment by kiryph** [comment]
@Eriner [You mentioned](https://github.com/Eriner/zim/issues/35#issuecomment-219255383) that you want to wait till certain issues have been resolved. I think the last one has been closed [26 days ago](https://github.com/zsh-users/zsh-autosuggestions/issues/141#issuecomment-266119072).

**Comment by lnicola** [comment]
The slow `mc` issue is still present.

**Comment by kiryph** [comment]
@Inicola sorry, I didn't see this. However, not everyone uses `mc`. I think, if it's disabled by default, it does not interfere with your usage. Adding a note to this module, that `mc` user shouldn't enable this, would be sufficient.

**Comment by lnicola** [comment]
@kiryph of course; I don't care either way. I was using something like @bijancn's method and `mc -u` (to disable the subshell), but I finally removed `zsh-autosuggestions` today.

**Comment by Vaesper** [comment]
[The mc issue](https://github.com/zsh-users/zsh-autosuggestions/issues/136) is closed now. Would really love to see this feature in zim.

**Comment by lnicola** [comment]
Works fine for me now, it seems. Unless I encounter any problems, I'd love to see this merged.

**Comment by bijancn** [comment]
Cool! Thanks a lot!
